# Generated by Django 3.2 on 2022-01-31 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='students.department'),
        ),
    ]
